import * as Yup from "yup";
const getSchema = (model = {}) => {
  const {
    patientId = 0,
    customerId = 41, //TODO must change this static value
    facilityId = 61,
    firstName = "",
    middleName = "",
    lastName = "",
    patientAge = 0,
    dateOfBirth = 10,
    maritalStatus = "", //constant value MARRIED, UNMARRIED
    gender = "", //constant value MALE, FEMALE
    patientContactNo = "",
    patientFatherName = "",
    patientMotherName = "",
    patientSpouseName = "",
    patientNextKeen = "",
    patientAddress = "",
    patientPoliceStation = "",
    patientPostOfficeId = 1,
    patientDistrictId = 1,
    patientCountryId = 1,
    patientNationalId = 1,
    patientBirthCertificateNo = 1,
    patientBloodGroup = "",
    emergencyContactName = "",
    emergencyContactNo = "",
    emergencyContactAddress = "",
    patientImage = "",
    patientPhotographId = 1,

  } = model;

  return {
    patientId,
    customerId,
    facilityId,
    firstName,
    middleName,
    lastName,
    patientAge,
    dateOfBirth,
    maritalStatus,
    gender,
    patientContactNo,
    patientFatherName,
    patientMotherName,
    patientSpouseName,
    patientNextKeen,
    patientAddress,
    patientPoliceStation,
    patientPostOfficeId,
    patientDistrictId,
    patientCountryId,
    patientNationalId,
    patientBirthCertificateNo,
    patientBloodGroup,
    emergencyContactName,
    emergencyContactNo,
    emergencyContactAddress,
    //patientImage,
    //patientPhotographId,
  };
};

const validator = Yup.object().shape({
  firstName: Yup.string().required('First Name is required'),
  //middleName: Yup.string().required('Middle Name is required'),
  //lastName: Yup.string().required('Last Name is required'),
  //patientAge: Yup.string().required('Age is required'),
  // customerId : Yup.string(),
  //   active : Yup.string(),
  //   userIp : Yup.string(),
  //   userId : Yup.string(),
  //   orgImage : Yup.string(),
  //   city : Yup.string(),
  //   patientContactNo : Yup.string(),
  //   country : Yup.string(),
  //   currency : Yup.string(),
  //   email : Yup.string(),
  //   fax : Yup.string(),
  //   orgAdd : Yup.string(),
  //   phone : Yup.string(),
  //   signatory : Yup.string(),
  //   state : Yup.string(),
  //   tin : Yup.string(),
  //   url : Yup.string(),
  //   vatRegNo : Yup.string(),
  //   orgName : Yup.string(),
  //   orgDsep : Yup.string(),
  //   centralZId : Yup.string(),
  //   musakno : Yup.string(),
  //   branch : Yup.string(),
  //   central : Yup.string(),
  //   curr : Yup.string(),
  //   madd : Yup.string(),
  //   file : Yup.string(),
  //   zutime : Yup.string(),
  //   xcountry : Yup.string(),
  //   xresource : Yup.string(),
  //   dformat : Yup.string(),
  //   zemail : Yup.string(),
});

export { getSchema, validator };

